# Generated by Django 4.1 on 2022-08-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacherApi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherSalaryModel",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="teacherApi.teacherdatacollection",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("monthly_salary", models.CharField(max_length=10)),
                ("paid_salary", models.CharField(max_length=10)),
                ("unpaid_salary", models.CharField(max_length=10)),
                ("total_salary", models.CharField(max_length=10)),
                ("date", models.DateField()),
            ],
        ),
    ]
