# Generated by Django 4.1 on 2022-09-16 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("teacherApi", "0004_teacherabsentmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeworkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("homework", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "teacher_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacherApi.teacherdatacollection",
                    ),
                ),
            ],
        ),
    ]
