# Generated by Django 4.1 on 2022-09-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherApi", "0006_alter_homeworkmodel_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherdatacollection",
            name="category",
            field=models.CharField(blank=True, default="Academic", max_length=50),
        ),
    ]
