# Generated by Django 4.1 on 2022-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
