# Generated by Django 4.1 on 2022-09-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcementmodel",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
