# Generated by Django 4.1 on 2022-09-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0002_alter_announcementmodel_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="TinyMceAnnouncementModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.TextField()),
            ],
        ),
    ]
