# Generated by Django 4.1 on 2022-09-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0004_newsmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsmodel",
            name="image",
            field=models.ImageField(blank=True, upload_to="image/news"),
        ),
    ]
