# Generated by Django 4.1 on 2022-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0005_newsmodel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsmodel",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
