# Generated by Django 4.1 on 2022-09-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0006_alter_newsmodel_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsmodel",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
