# Generated by Django 4.1 on 2022-09-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0007_alter_newsmodel_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("paragraph_one", models.TextField()),
                ("paragraph_two", models.TextField(blank=True)),
                ("paragraph_three", models.TextField(blank=True)),
                ("short_details", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("status", models.BooleanField(default=True)),
                ("author_name", models.CharField(max_length=100)),
                ("author_img", models.ImageField(blank=True, upload_to="image/author")),
                ("image", models.ImageField(upload_to="image/news")),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
