# Generated by Django 4.1 on 2022-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0008_blogmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="image",
            field=models.ImageField(blank=True, upload_to="image/news"),
        ),
    ]
