# Generated by Django 4.1 on 2022-09-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0009_alter_blogmodel_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("location", models.CharField(max_length=100)),
                ("status", models.BooleanField(default=True)),
            ],
        ),
    ]
