# Generated by Django 4.1 on 2022-09-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0010_eventsmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=30)),
                ("subject", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("exam_term", models.CharField(max_length=50)),
            ],
        ),
    ]
