# Generated by Django 4.1 on 2022-09-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0011_routinemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveApplicationModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("days", models.IntegerField()),
                ("reason", models.TextField()),
                ("status", models.CharField(default="pending", max_length=50)),
            ],
        ),
    ]
