# Generated by Django 4.1 on 2022-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0012_leaveapplicationmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEventModel",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        max_length=1000, primary_key=True, serialize=False
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("all_day", models.BooleanField(default=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
