# Generated by Django 4.1 on 2022-09-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0013_calendareventmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionInquiryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=20)),
                ("date_of_birth", models.CharField(max_length=20)),
                ("entering_grade", models.CharField(max_length=30)),
                ("year_applying", models.CharField(max_length=20)),
                ("current_school", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=50)),
                ("home_phone", models.CharField(max_length=10)),
                ("relation", models.CharField(max_length=50)),
                ("prefix", models.CharField(max_length=10)),
                ("guardian_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("hear_about_school", models.CharField(blank=True, max_length=100)),
                ("additional_query", models.TextField(blank=True)),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
