# Generated by Django 4.1 on 2022-09-04 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0014_admissioninquirymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("category", models.CharField(max_length=50)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=True)),
                ("image", models.ImageField(upload_to="image/collection/")),
            ],
        ),
    ]
