# Generated by Django 4.1 on 2022-09-17 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0015_gallerymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaveapplicationmodel",
            name="days",
        ),
    ]
