# Generated by Django 4.1 on 2022-09-17 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0011_alter_studentdatacollection_email"),
        ("infoApi", "0016_remove_leaveapplicationmodel_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplicationmodel",
            name="stu_id",
            field=models.ForeignKey(
                default="4DHIEG563",
                on_delete=django.db.models.deletion.CASCADE,
                to="studentApi.studentdatacollection",
            ),
            preserve_default=False,
        ),
    ]
