# Generated by Django 4.1 on 2022-09-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0017_leaveapplicationmodel_stu_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallerymodel",
            name="category",
        ),
        migrations.RemoveField(
            model_name="gallerymodel",
            name="status",
        ),
    ]
