# Generated by Django 4.1 on 2022-09-22 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infoApi", "0018_remove_gallerymodel_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="announcementmodel",
            old_name="paragraph_one",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="blogmodel",
            old_name="paragraph_one",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="newsmodel",
            old_name="paragraph_one",
            new_name="data",
        ),
        migrations.RemoveField(
            model_name="announcementmodel",
            name="paragraph_three",
        ),
        migrations.RemoveField(
            model_name="announcementmodel",
            name="paragraph_two",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="paragraph_three",
        ),
        migrations.RemoveField(
            model_name="blogmodel",
            name="paragraph_two",
        ),
        migrations.RemoveField(
            model_name="newsmodel",
            name="paragraph_three",
        ),
        migrations.RemoveField(
            model_name="newsmodel",
            name="paragraph_two",
        ),
    ]
