# Generated by Django 4.1 on 2022-08-28 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAttendanceModel",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="studentApi.studentdatacollection",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("attend_day", models.CharField(max_length=5)),
                ("absent_day", models.CharField(max_length=5)),
                ("total_day", models.CharField(max_length=5)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentAbsentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("date", models.DateField()),
                (
                    "student_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentApi.studentdatacollection",
                    ),
                ),
            ],
        ),
    ]
