# Generated by Django 4.1 on 2022-08-28 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0002_studentattendancemodel_studentabsentmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFeeModel",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="studentApi.studentdatacollection",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("monthly_fee", models.IntegerField()),
                ("bus_fee", models.IntegerField()),
                ("computer_fee", models.IntegerField()),
                ("paid_fee", models.BigIntegerField()),
                ("unpaid_fee", models.BigIntegerField()),
                ("total_fee", models.BigIntegerField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="StudentFeePaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("amount", models.IntegerField()),
                ("date", models.DateField()),
                (
                    "student_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentApi.studentdatacollection",
                    ),
                ),
            ],
        ),
    ]
