# Generated by Django 4.1 on 2022-08-28 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0003_studentfeemodel_studentfeepaymentmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentResultCollectionModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=50)),
                ("total_marks", models.IntegerField()),
                ("pass_marks", models.IntegerField()),
                ("obtained_marks", models.IntegerField()),
                ("gpa", models.CharField(max_length=5)),
                ("exam_term", models.CharField(max_length=15)),
                (
                    "stu_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentApi.studentdatacollection",
                    ),
                ),
            ],
        ),
    ]
