# Generated by Django 4.1 on 2022-08-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0004_studentresultcollectionmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentresultcollectionmodel",
            name="grade",
            field=models.CharField(default="One", max_length=50),
        ),
    ]
