# Generated by Django 4.1 on 2022-08-30 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0005_studentresultcollectionmodel_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendancemodel",
            name="grade",
            field=models.CharField(default="One", max_length=20),
        ),
    ]
