# Generated by Django 4.1 on 2022-08-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0006_studentattendancemodel_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeemodel",
            name="grade",
            field=models.CharField(default="One", max_length=20),
        ),
    ]
