# Generated by Django 4.1 on 2022-08-30 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0007_studentfeemodel_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdatacollection",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
