# Generated by Django 4.1 on 2022-08-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0009_alter_studentdatacollection_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdatacollection",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
