# Generated by Django 4.1 on 2022-08-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentApi", "0010_alter_studentdatacollection_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdatacollection",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
